apiVersion: v1
kind: Service
metadata:
  labels:
    run: devops
  name: devops
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 4567
    protocol: TCP
    targetPort: 4567
  selector:
    run: devops
  sessionAffinity: None
  type: NodePort